version: '3.8'

services:
  mtl-resources-mpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtl-resources-mpc
    ports:
      - "8501:8501"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./.streamlit:/app/.streamlit
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - mtl-network

networks:
  mtl-network:
    driver: bridge 