version: '3.8'

services:
  mtl-scrapmeup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtl-scrapmeup
    ports:
      - "8502:8502"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./.streamlit:/app/.streamlit
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - mtl-network

networks:
  mtl-network:
    driver: bridge 